### ISSUE TITLE
Example sent even if there is not an actual example (assistant) reply

### ISSUE THREAD

**Issue by bfs15** [Cohee1207/SillyTavern#210]
**Describe the bug**

Examples can be sent even when theres no point to them
given the card with chat examples (this bug happens often when Y is not short):
```
<START>
{{user}}: I do X
{{char}}: I respond Y
```
Whenever "I respond Y" doesn't fit the context, but "I do X" does, it sends
```
[Start chat]
user: I do X
[Start chat]
[... actual chat]
```
which is useless, no actual example response.

I ended up implementing the fix in my Spermack fork which uses Slack's Claude and modifies the message in that way before formatting for Slack
But the problem is there on OpenAI's GPT at least, which I tested.
the changelog was "Now it removes the example if there is not an actual example (assistant) reply"

**To Reproduce**

Create a card in with this in the chat examples: 
```
<START>
{{user}}: I do X
{{char}}: I respond Y
```
but make Y a large number of characters, so you always trigger the bug.

**Expected behavior**

Example is omitted if there isn't a single Assistant reply

**Desktop (please complete the following information):**
 - OS/Device: W10
 - Environment: local
 - Browser chrome
 - Generation API: tested on OpenAI
 - Branch dev
 - Model GPT-3.5

**Additional context**

**Comment by gidzzz** [comment]
If I understand correctly, the problem is that OpenAI handler has completely independent logic for processing examples and the difference is this:
* In `script.js`, we try to fit an entire example block at once, consisting of multiple messages. If it does not fit, we discard the entire block.
* in `openaj.js`, we split example block into individual messages in `parseExampleIntoIndividual()` and later try to fit those messages independently, leading to mutilated examples.

So I think the problem is not with example blocks which do not have user responses – if for some reason someone wants such example, I'd say let's allow it, it's their choice. The problem is that in OpenAI code we allow cutting an example block in half, leading to incomplete examples, and 7b9e04258928ef80547cbcdca593fec773fa7fe9 does not address it.

**Comment by gidzzz** [comment]
Do you think maybe #211 makes more sense?

**Comment by bfs15** [comment]
thanks!
