### ISSUE TITLE
[Feature Request]  Streaming stop button relocation💬, Stop Generation Faster. 🛑

### ISSUE THREAD

**Issue by imesha10** [Cohee1207/SillyTavern#329]
**Is your feature request related to a problem? Please describe.**
_See examples below._
1. When a new message is being streamed at the bottom the stop button moves positions as in the example below.
2. Please add support so that it is possible to cancel a generation right after you start it, there seems to be a delay where it's just loading.

**Describe the solution you'd like**
1. It might be better to just temporary replace the hourglass at the bottom with the stop button while the text is streaming and get rid of the stop button at the side of the message.
3. Add functionality to stop the text generation so that it can be stopped immediately or faster (I don't know if this will cause problems).

**Describe alternatives you've considered**
None.

**Additional context**
### Example for 1

https://github.com/Cohee1207/SillyTavern/assets/16441743/9bec185c-05fc-4d31-8c6c-d1b32cb72a84

### Example for 2

https://github.com/Cohee1207/SillyTavern/assets/16441743/5913e707-4ba4-4263-a42b-543b6b6c63a0

**Comment by RossAscends** [comment]
The conflict here is that "hourglass" means "a messaging routine is underway in the background". It's a way to prevent user from spamming multiple requests to the backend server and interrupting things. 

"Stop button" means "stop the current incoming response stream". This also _happens to_ stop the background routine. 

They mean different things. 

I do not think we can manually interrupt backends that are currently processing a prompt, if they are not currently streaming a response. 

So putting the stop button in the send form instead of the hourglass would be misleading and frustrating for the user.

**Comment by imesha10** [comment]
I see, it seems that the moving stop button seems to be fixed so it feels much better, thanks.
