### ISSUE TITLE
Custom preset that remembers changes

### ISSUE THREAD

**Issue by Omniphantasm** [Cohee1207/SillyTavern#75]
Any chance we can get a slot or two that remembers values we put into it between sessions/page refreshes? 

Ideally we could name them but even Custom 1/2/3 would be enough. Most important thing is it'd be nice to have a few slots we can have set up how we want easily through the GUI itself.

**Comment by RossAscends** [comment]
Can you be more clear about this? What are you wanting to customize?

**Comment by Omniphantasm** [comment]
[These](https://i.imgur.com/Kb60Qbw.png) The ones that are there now reset when you refresh the page, it'd be helpful to have a few custom slots that don't do that and can be tweaked from the GUI and saved for future use.

**Comment by RossAscends** [comment]
They reset because you are using a preset, which has a fixed values declared inside the preset file. 

It sounds like you are wanting the ability to make custom presets for KoboldAI. 

Currently this can be achieved by selecting "GUI KoboldAI settings", and then opening your KoboldAI settings page to tweak the settings there. 

We will consider adding the ability to create new preset files inside SillyTavern.

**Comment by Necroxix** [comment]
What I've been doing is creating a copy of a preset file in the /public/koboldai settings or /public/textgen settings folders, renaming it, and changing the settings in the file to my liking.

**Comment by Omniphantasm** [comment]
Aye, that's what I've been doing as well. 

It works but it's not ideal.
